name: Build and Deploy CJD80

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Type check
        run: npm run check

      - name: Build application
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy to production
        run: |
          # Create deployment tarball
          tar -czf /tmp/deploy.tar.gz --exclude=node_modules --exclude=.git .
          
          # Transfer to production
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 /tmp/deploy.tar.gz ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/tmp/
          
          # Deploy on production server
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} << 'ENDSSH'
            cd /opt/cjd80
            
            # Backup current version
            [ -d app-backup ] && rm -rf app-backup
            [ -d app ] && mv app app-backup
            
            # Extract new version
            mkdir -p app
            tar -xzf /tmp/deploy.tar.gz -C app
            rm -f /tmp/deploy.tar.gz
            
            # Rebuild Docker image
            cd app
            docker build -t cjd80-app:latest .
            
            # Restart services
            cd /opt/cjd80
            docker compose down
            docker compose up -d
            
            echo "Deployment completed at $(date)"
            sleep 10
            docker compose ps
          ENDSSH

      - name: Verify deployment
        run: |
          sleep 20
          curl -sf https://cjd80.fr/api/health && echo "Health check passed" || echo "Health check - service starting"
