name: Build and Deploy CJD80

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: gitea.robinswood.io
  IMAGE_NAME: cjd80

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Type check
        run: npm run check

      - name: Build application
        run: npm run build

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy to production server
        run: |
          echo "Deployment step - will be configured with SSH action later"
          echo "For now, deploy manually via: docker save | ssh load"
