name: Build and Deploy CJD80

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: cjd80-app
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Type check
        run: npm run check

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} | gzip > /tmp/cjd80-app.tar.gz
          ls -lh /tmp/cjd80-app.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Transfer and deploy
        run: |
          # Transfer image
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 /tmp/cjd80-app.tar.gz ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/tmp/
          
          # Load and restart
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} << 'ENDSSH'
            cd /opt/cjd80
            gunzip -c /tmp/cjd80-app.tar.gz | docker load
            docker compose down
            docker compose up -d
            rm -f /tmp/cjd80-app.tar.gz
            echo "Deployment completed at $(date)"
            sleep 10
            docker compose ps
          ENDSSH

      - name: Verify deployment
        run: |
          sleep 20
          curl -sf https://cjd80.fr/api/health && echo "Health check passed" || echo "Health check - service starting"
